export type Size = 'tiny' | 'small' | 'normal' | 'big' | 'large'
export type Color =
  | 'primary'
  | 'success'
  | 'warning'
  | 'error'
  | 'normal'
  | 'light'
  | 'dark'
  | 'gray'
  | 'input'
  | 'white'
